language: node_js
node_js:
  - "10"
dist: trusty
script:
  - npm run concurrentlyScripts
install:
  - npm run CiAll
cache:
  directories:
    - ~/.npm
    - ~/.cache
branches:
  only:
    - master
    - Cypress
    - feature/travisFix
