language: node_js
node_js:
  - "10"
script:
  - npm run concurrentlyScripts
install:
  - npm ci && npm run CiAll
cache:
  directories:
    - ~/.npm
    - ~/.cache
branches:
  only:
    - master
    - Cypress
    - feature/travisFix
