language: node_js
node_js:
  - "10"
script:
  - npm run installAll
  - npm run standard & npm run test & npm run e2e
# install:
#  - npm ci
cache:
  directories:
    - ~/.npm
    - ~/.cache
branches:
  only:
    - master
    - Cypress
    - feature/travisFix
