language: node_js
node_js:
  - "10"
script:
  - npm run CiAll
  - npm run concurrently
install:
  - npm ci
cache:
  directories:
    - ~/.npm
    - ~/.cache
branches:
  only:
    - master
    - Cypress
    - feature/travisFix
