language: node_js
node_js:
  - "10"
script:
  - npm run installAll
  - npm run standard
  - npm run test
  - npm run e2e
cache:
  directories:
    - ~/.npm
    - ~/.cache
env:
  CYPRESS_RECORD_KEY: "ba1a87f5-afb6-4f71-aad1-def58f48e95b"